# Generated by Django 2.2.24 on 2024-06-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20240618_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Defence',
            new_name='defence',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Health',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Stamina',
            new_name='stamina',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Strength',
            new_name='strength',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default='Дата и время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default='Дата и время исчезновения'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entity', to='pokemon_entities.Pokemon', verbose_name='Ссылка на покемона'),
        ),
    ]
